---
- name: Print Hello World and set as fact
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Print Hello World
      ansible.builtin.debug:
        msg: 'Hello world'

    - name: Print event information
      ansible.builtin.debug:
        msg: '{{ ansible_eda.event }}'
      when: ansible_eda is defined

    - name: Print event information
      ansible.builtin.debug:
        msg: 'ansible_eda variable is not defined, is prompt on launch active?'
      when: ansible_eda is not defined

    - name: Set msg fact
      ansible.builtin.set_fact:
        msg: 'hello world'
        cacheable: true
...
